[package]
name = "ext"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking"] }
extism = "1.6.0"
color-eyre = "0.6"
url = "2.5.2"


[profile.dev.package.backtrace]
opt-level = 3
